- name: Deploy to AWS EC2 via SSH
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      # remove old app folder
      rm -rf /home/ubuntu/app || true

      # clone latest code from GitHub
      git clone https://github.com/${{ github.repository }} /home/ubuntu/app

      # go inside app folder
      cd /home/ubuntu/app/app

      # stop and remove old container
      docker stop drviki-app || true
      docker rm drviki-app || true

      # build and run new Docker container
      docker build -t drviki-app .
      docker run -d -p 8080:8080 --name drviki-app drviki-app
